name: companox
description: Your companion

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_icons: ^1.1.0
  curved_navigation_bar: ^0.3.2
  font_awesome_flutter: ^8.8.1
  firebase_auth: ^0.20.1
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0+1
  firebase_storage: ^7.0.0
  firebase_analytics: ^7.0.1
  google_sign_in: ^4.5.1
  image_picker: ^0.6.6+1
  uuid: ^2.0.4
  path_provider: ^1.6.8
  animations: ^1.0.0+5
  geolocator: ^5.3.1
  cached_network_image: ^2.2.0+1
  animator: ^2.0.0
  timeago: ^3.0.2
  firebase_messaging: ^6.0.16
  image: ^2.1.19
#  multi_image_picker: ^4.6.7
#  searchable_dropdown: ^1.1.3
#  flutter_multiselect: ^0.5.0
  getwidget: ^1.2.4
  eva_icons_flutter: ^2.0.0
#  flutter_image_compress: ^0.7.0
#  checkbox_formfield: ^0.1.0+3
  community_material_icon: 3.5.95
  frino_icons: ^1.0.1
  flutter_svg: ^0.19.0
  json_annotation: ^3.0.1
  provider: ^4.1.3
  flutter_auth_buttons: ^0.8.0
#  number_inc_dec: ^0.5.0
#  carousel_slider: ^2.2.1
  image_cropper: ^1.2.3
  modal_progress_hud: ^0.1.3
#  inview_notifier_list: ^0.0.4
#  quill_delta: ^1.0.0
  flutter_markdown: ^0.4.2
  permission_handler: 3.0.0
  emoji_picker: ^0.1.0
#  photo_view: ^0.10.3
  fluttertoast: ^3.1.3
#  http: ^0.12.1
  #  firebase_ml_vision: ^0.9.4
#  rxdart: 0.25.0
#  paginate_firestore: ^0.3.0
#  dropdown_formfield: ^0.1.2
#  country_icons: ^1.1.1
#  transparent_image: ^1.0.0
#  smart_select: ^4.3.2
#  flutter_currencies_tracker: ^0.0.4
#  country_list_pick: ^1.0.1+3
  get: ^3.24.0
#  smooth_star_rating: 1.1.1
  #  zego_express_engine: ^2.2.0
  #  agora_rtc_engine: ^1.0.13
  #  agora_rtm: ^0.9.11
#  sliding_up_panel: ^1.0.2
  wakelock: any
#  intl: ^0.16.0
  gradient_text: 1.0.2
#  flare_flutter:
  random_color: ^1.0.5
  alert_dialog: ^0.2.0
#  badges: ^1.1.6
#  animated_text_kit: ^3.1.2
  auto_size_text: ^2.1.0
  buttons_tabbar: ^1.1.2
#  sizer: ^1.1.8
  url_launcher: ^6.0.4
#  auto_search: ^1.0.6
  bubble_tab_indicator: ^0.1.4
  curved_splash_screen: ^1.0.0
  splashscreen: ^1.3.5
  custom_splash: ^0.0.2
  animated_splash_screen: ^1.0.1+2
#  back_pressed: ^0.0.2
  modal_bottom_sheet: ^2.0.0
#  flutter_chip_tags: ^1.0.4
#  flutter_country_picker: ^0.1.6
  flutter_animated_button: ^2.0.0
  neon: ^0.0.1
  custom_timer: ^0.0.6
  bottom_bar: ^1.2.4
  google_fonts: ^1.1.2
#  insta_html_parser: ^0.1.1
#  ssinstafeedparser: ^0.0.1
#  neeko: ^0.0.10
  simple_polls: ^1.0.6
  flutter_sticky_header: ^0.6.0
  simple_speed_dial: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

#   To add assets to your application, add an assets section, like this:
  assets:
    - assests/img/COMPANOX.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
